config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  match 'process-refunds', to: 'home#process_refunds', via: [:post]
  match 'import-orders', to: 'home#import_orders', via: [:get]
  match 'import-orders', to: 'home#import_orders', via: [:post]
  match 'import-complete', to: 'home#import_complete', via: [:get]
  match 'refund-order', to: 'home#refund_order', via: [:post]  
  match 'calculate-and-process-refund', to: 'home#calculate_and_process_refund', via: [:post]
  match 'create-order-dom-object', to: 'home#create_order_dom_object', via: [:post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :lively_refund
end

app/models/lively_refund.rb
class LivelyRefund < ActiveRecord::Base
	has_many :line_items
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  include ShopifyApp::SessionStorage
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController  

  def index
    @orders = ShopifyAPI::Order.find(:all, params: { limit: 100 })
    @products = ShopifyAPI::Product.find(:all, params: { limit: 100 })
  end

  def import_complete

  end

  def import_orders
  	@file = params[:file]
  	if @file
  		@uploaded_items_to_refund = import_orders_for_refund(@file)
  	else
  		flash.now[:error] = "Please select a file to upload."
  	end	
  end

  def refund_order
  	items_to_refund = []
	order_id = params[:orderId].to_i
	@order = GetOrderJob.perform_now(order_id)
	sleep 2.0
  	refund_line_items = JSON.parse(params[:lineItems])
  	refund_line_items.each do |line_item|
		line_item_object = @order.line_items.select { |i| i.sku == line_item["lineItemSku"].to_s }.first
		items_to_refund << {
			line_item_id: line_item_object.id,
    		quantity: line_item["quantity"]
		} if line_item
	end
	formatted_refund = {
	    :shipping => {
			:full_refund => false
	    },
	    :refund_line_items => items_to_refund
    }
	if @order && formatted_refund && (!@order.is_a? String)
		@calculated_refund = calculate_refund(formatted_refund, @order)
		unless @calculated_refund.is_a? Hash
			@refund = create_refund_object(@order, @calculated_refund)
			if @refund && !@calculated_refund.attributes["refund_line_items"].empty?
				render :json => { 
					:status => :ok, 
					:order	=> @order,
					:refund => @refund
				}
			elsif @refund && @calculated_refund.attributes["refund_line_items"].empty?
				render :json => { 
					:status => :error, 
					:message => "An error occured while refunding order ##{@order.order_number}. One or more of the SKUs are likely incorrect.",
					:order	=> @order
				}		
			else
				render :json => { 
					:status => :ok, 
					:message => "Failure!!", 
					:html => "...insert html..." 
				}
			end
		else
			render :json => { 
				:status => :error, 
				:message => @calculated_refund[:message],
				:order	=> @calculated_refund[:order]
			}
		end
  	else
  		render :json => { 
			:status => :critcal, 
			:message => "An error occured while importing your return file. Resource Not Found"
		}
  	end
  end 

  def create_order_dom_object
  	items_to_refund_array = []
  	invalid_line_items_array = []
	order_id = params[:orderId].to_i
	order_num = params[:orderNum].to_i
  	refund_line_items = JSON.parse(params[:lineItems])
	@order = GetOrderJob.perform_now(order_id) 
	sleep 1	
	if	@order && (!@order.is_a? Hash)
	  	refund_line_items.each do |line_item|
			line_item_object = @order.line_items.select { |i| i.sku == line_item["item_num"].to_s }.first || "invalid"
			if line_item_object === "invalid"
				line_item["name"] = "Invalid Shopify SKU"
				line_item["price"] = "N/A"
				invalid_line_items_array << line_item
			else
				line_item["name"] = line_item_object.name
				line_item["price"] = line_item_object.price
				items_to_refund_array << line_item
			end	
		end
	else 
		refund_line_items.each do |line_item|
			line_item["name"] = "Invalid Shopify SKU"
			line_item["price"] = "N/A"
			invalid_line_items_array << line_item
		end
	end	
	items_to_refund = items_to_refund_array.empty? ? false : items_to_refund_array.group_by { |i| i["order_num"] }
	invalid_line_items = invalid_line_items_array.empty? ? false : invalid_line_items_array.group_by { |i| i["order_num"] }
	if items_to_refund && !items_to_refund.empty?
		render :json => { 
			:status => :ok,
			:orderId => order_id,
			:orderNum => order_num,
			:itemsToRefund => items_to_refund,
			:invalidLineItems => invalid_line_items
		}
	elsif invalid_line_items && !invalid_line_items.empty?
		render :json => { 
			:status => :ok,
			:orderId => order_id,
			:orderNum => order_num,
			:itemsToRefund => [],
			:invalidLineItems => invalid_line_items
		}
	else	
		render :json => { 
			:status => :error, 
			:message => "Failure!! There was a problem with one of your orders."
		}
	end
  end

  private

	def calculate_refund(data, order)
		puts "CALCULATING..."
		begin
			ShopifyAPI::Refund.calculate(data, :params => {:order_id => order.id})
		rescue ActiveResource::ResourceConflict
			"An error occured while importing your return file. Resource Conflict"
		rescue ActiveResource::ResourceInvalid 
			{
				message: "An error occured while importing ORDER ##{order.order_number}. This type of error is generally caused when attempting to refund an item that has already been refunded.",
				order: order
			}	
		end
	end

	def create_refund_object(order, calculated_refund)
		calculated_refund.transactions.each {|t| t.kind = "refund"}
		refund = ShopifyAPI::Refund.create(
	      :order_id => order.id,
	      :note => "Refund administered via LIVELY Returns App",
	      :restock => false,
	      :shipping => { :full_refund => false },
	      :refund_line_items => calculated_refund.refund_line_items,
	      :transactions => calculated_refund.transactions,
	      :notify => true
	    )
	end

	def import_orders_for_refund(file)
		if file
			csv_file_path = file.tempfile if file

			valid_items = []
			flagged_items = []

			all_items_submitted_for_refund = {
				valid_skus: [],
				invalid_skus: []
			}
			
			items_to_refund = []
			
			CSV.foreach(csv_file_path, :headers => true) do |row|
				order_num = row.to_hash["Ext Order #"][3..-1].to_i
				order_id = row.to_hash["Shopify Order ID"]
				sku = row.to_hash["Item #"]
				reason_code = row.to_hash["Reason Code"]
				quantity = row.to_hash["QTY RTND"].to_i
				quality = row.to_hash["Quality"].to_i
				item_to_refund = {
					order_num: order_num,
					order_id: order_id,
					reason_code: reason_code,
					sku: sku,
					quantity: quantity,
					quality: quantity
				}
				valid_items << item_to_refund
			end	
	
			all_items_submitted_for_refund[:valid_skus] << valid_items.group_by { |i| i[:order_num] } unless valid_items.blank?
			all_items_submitted_for_refund[:invalid_skus] << flagged_items unless flagged_items.empty?
			return all_items_submitted_for_refund
		else
			return false

		end	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/views/home/import_complete.html.erb
<%- if flash[:success] %>
  <p class="success">
    <%= flash[:success] %>
  </p>
<%- elsif flash[:error] %>
  <p class="error">
    <%= flash[:error] %>
  </p>
<%- end %> 

<%- flash.clear %>

app/views/home/import_orders.html.erb
<nav>
  <div class="pure-g">
    <div class="grid-column pure-u-1">
      <div class="container">
        <ul>
        	<li>
            <%= link_to "Dashboard", root_path %>
          </li>
          <li>
            <%= link_to "Import Orders", import_orders_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>
<div class="pure-g">
  <div class="grid-column pure-u-1">
    <div class="container">
      <div class="flash--message__wrapper">
          <%- if flash[:success] %>
            <p class="success">
              <%= flash[:success] %>
            </p>
          <%- elsif flash[:error] %>
            <p class="error">
              <%= flash[:error] %>
            </p>
          <%- end %> 
      </div>
      <div class="pure-g">
        <div class="grid-column pure-u-1">
          <header>
            <h1>
              Import Orders for Refund
            </h1>
          </header>
        </div>
        <div class="grid-column pure-u-1">
          <%- if flash[:message] %>
              <p class="message">
                <%= flash[:message] %>
              </p>
          <%- end %>
          
          <%- if @uploaded_items_to_refund && @uploaded_items_to_refund[:valid_skus] && !@uploaded_items_to_refund[:valid_skus].empty? %>
            <%- @uploaded_items_to_refund[:valid_skus][0].each do |key,value| %>
              <span class="uploaded--order__container">
                <%- value.each do |line_item| %>
                  <span 
                    class="line-item__container"
                    data-upload-order-id = "<%= line_item[:order_id] %>"
                    data-upload-order-num = "<%= line_item[:order_num] %>"
                    data-upload-line-item-sku = "<%= line_item[:sku] %>"
                    data-upload-line-item-reason-code = "<%= line_item[:reason_code] %>"
                    data-upload-line-item-quantity = "<%= line_item[:quantity] %>"
                    data-upload-line-item-quality = "<%= line_item[:quality] %>"
                  >
                  </span>
                <% end %>
              </span>  
            <% end %>
          <%- end %>

      		<%- unless (@formatted_refunds && @formatted_refunds[:valid_refunds] && !@formatted_refunds[:valid_refunds].empty?) || @uploaded_items_to_refund && !@uploaded_items_to_refund.empty? %>
            <%= form_tag import_orders_path, multipart: true do %>
      			  <%= file_field_tag :file %>
      			  <%= submit_tag "Import" %>
      			<%- end %>
          <%- end %>
        </div>
        <div class="orders__container grid-column pure-u-1">
          <%- if @formatted_refunds && @formatted_refunds[:valid_refunds] && !@formatted_refunds[:valid_refunds].empty?  %>
          <h2>
            Valid refund line items
          </h2>
            <%- @formatted_refunds[:valid_refunds].each do |formatted_refund| %>
              <div class="order__container" data-order-id-container="<%=formatted_refund[:refund_line_items].first[:order_id]%>">
                <table>
                  <thead>
                    <tr>
                      <td>
                        <h4>
                          Shopify ID
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Order Number
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Variant Name
                        </h4>
                      </td>
                      <td>
                        <h4>
                          SKU
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Price
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Quantity
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Quality
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Reason for Return
                        </h4>
                      </td>
                    </tr>  
                  </thead>
                  <tbody>  
                    <%- formatted_refund[:refund_line_items].each do |line_item|%>
                      <tr class="line-item__row" data-reason-code="<%=line_item[:reason_code]%>" data-quantity="<%=line_item[:quantity]%>" data-line-item-id="<%=line_item[:line_item_id]%>">
                        <td>
                          <p>
                            <%= line_item[:order_id] %>
                          </p>
                        </td>
                        <td>
                          <a target="_blank" href="https://wearlively.com/admin/orders/<%= line_item[:order_id]%>">
                            <%= line_item[:order_num] %>
                          </a>
                        </td>
                        <td>
                          <p>
                            <%= line_item[:name] %>
                          </p>
                        </td>
                        <td>
                          <p>
                            <%= line_item[:sku] %>
                          </p>
                        </td>
                        <td class="<%- if line_item[:price].to_f <= 10.00 %>flag money <%- end %>">
                          <p>
                            $<%= line_item[:price] %>
                          </p>
                        </td>
                        <td>
                          <p>
                            <%= line_item[:quantity] %>
                          </p>
                        </td>
                        <td>
                          <p>
                            <%= line_item[:quality] %>
                          </p>
                        </td>
                        <td>
                          <p>
                            <%= line_item[:reason_code] %>
                          </p>
                        </td>
                      </tr>  
                    <%- end %>
                  </tbody>
                </table>
                <div class="feedback__container">
                  
                </div>
                <button class="btn process--refund" data-order-id="<%=formatted_refund[:refund_line_items].first[:order_id]%>">
                  Process refund for Order #: <%= "#{formatted_refund[:refund_line_items].first[:order_num]}" %>
                </button>
              </div>  
            <%- end %> 
			    <%- end%>
        </div>


        <div class="grid-column pure-u-1">
          <%- if @formatted_refunds && @formatted_refunds[:invalid_refunds] && !@formatted_refunds[:invalid_refunds].empty? && !@formatted_refunds[:invalid_refunds][0][:refund_line_items].empty? %>
            <h2>
              Refund Line Items with invalid SKUS
            </h2>
            <p>
              The following line items  cannot be refunded via this application. To attempt to process any of them, please do so via Shopify's admin panel.
            </p>
            <%- @formatted_refunds[:invalid_refunds].each do |formatted_refund| %>
              <div class="order__container">
                <table>
                  <thead>
                    <tr>
                      <td>
                        <h4>
                          Shopify ID
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Order Number
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Message
                        </h4>
                      </td>
                      <td>
                        <h4>
                          SKU
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Price
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Quantity
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Quality
                        </h4>
                      </td>
                      <td>
                        <h4>
                          Reason for Return
                        </h4>
                      </td>
                    </tr>  
                  </thead>
                  <tbody>  
                    <%- formatted_refund[:refund_line_items].each do |line_item|%>
                      <tr>
                        <td>
                          <p>
                            <%= line_item[:order_id] %>
                          </p>
                        </td>
                        <td>
                          <a target="_blank" href="wearlively.com/admin/orders/<%= line_item[:order_id]%>">
                            <%= line_item[:order_num] %>
                          </a>
                        </td>
                        <td>
                          <p>
                            <%= line_item[:name] %>
                          </p>
                        </td>
                        <td class="flag">
                          <p>
                            <%= line_item[:sku] %>
                          </p>
                        </td>
                        <td>
                          <p>
                            $<%= line_item[:price] %>
                          </p>
                        </td>
                        <td>
                          <p>
                            <%= line_item[:quantity] %>
                          </p>
                        </td>
                        <td>
                          <p>
                            <%= line_item[:quality] %>
                          </p>
                        </td>
                        <td>
                          <p>
                            <%= line_item[:reason_code] %>
                          </p>
                        </td>
                      </tr>  
                    <%- end %>
                  </tbody>
                </table>
              </div>  
            <%- end %> 
          <%- end%>
        </div>
      </div>      
    </div> 
  </div>   
</div>
<%- flash.clear %>

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Home",
        icon: "<%= asset_path('favicon.ico') %>"
      });
    });
  </script>
<% end %>

<nav>
  <div class="pure-g">
    <div class="grid-column pure-u-1">
      <div class="container">
        <ul>
          <li>
            <%= link_to "Dashboard", root_path %>
          </li>
          <li>
            <%= link_to "Import Orders", import_orders_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

<div class="pure-g">
  <div class="grid-column pure-u-1">
    <div class="container">
      <div class="flash--message__wrapper">
          <%- if flash[:success] %>
            <p class="success">
              <%= flash[:success] %>
            </p>
          <%- elsif flash[:error] %>
            <p class="error">
              <%= flash[:error] %>
            </p>
          <%- end %> 
      </div>
      <%- flash.clear %>
      <div class="pure-g">
        <div class="grid-column pure-u-1">
          <header>
            <h1>
              LIVELY | Returns
            </h1>
          </header>
        </div>
    </div>      
  </div>  
</div>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReturnsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>